# Datenverarbeitung mit Pandas und Regression mit Scikit-Learn

Mit diesem Übungsblatt verfolgend wir zwei Ziele: Erstens wollen wir Ihnen zeigen, wie Sie die grundlegenden Funktionen der Bibliotheken [Pandas](https://pandas.pydata.org/) und [Scikit-learn](https://scikit-learn.org/stable/) verwenden. Diese beiden Bibliotheken sind die Standardbibliotheken für Datenanalyse und maschinelles Lernen in Python. 
Zweitens möchten wir, dass Sie selbst einfache Modelle für Regression erstellen und diese evaluieren können. Dabei sollen die in der Vorlesung vorgestellten Konzepte angewendet werden.

*Hinweis:* Sie können viele der Aufgaben lösen, indem Sie die Beispiel aus dem Jupyter-Notebook zur Vorlesung (siehe Moodle) anpassen. Zudem haben wir Ihnen auch immer die Links zur Dokumentation der verwendeten Funktionen bereitgestellt. Auch da finden Sie viele Beispiele, die Ihnen helfen sollten.

In [2]:
import numpy as np
import matplotlib.pyplot as plt

#
# Neue imports für pandas und scikit-learn
#
import pandas as pd
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split

# Einführung: Manipulieren von Daten mit Pandas

In den bisherigen Beispielen haben wir vor allem mit Numpy-Arrays gearbeitet. Für das Manipulieren von grösseren Datensätzen mit vielen Variablen, wie wir dies in typischen Machine Learning Anwendungen häufig sehen, ist numpy aber nicht geeignet. Wir können dafür stattdessen die Bibliothek [Pandas](https://pandas.pydata.org/) verwenden. Pandas bietet viele nützliche Funktionen für die Darstellung der Daten, das Auswählen von Teilmengen der Daten, sowie Sortieren und Gruppieren der Daten. So kann man zum Beispiel Variablen nach Namen auswählen und muss nicht immer mit numerischen Indizes arbeiten. Ausserdem kann ein Pandas-Dataframe, im Gegensatz zu einem Numpy-Array, Zeilen oder Spalten mit verschiedenen Datentypen enthalten.

Hier sehen Sie einige Beispiele, die für die Bearbeitung des Übungsblatts nützlich sind.

Als erstes erstellen wir uns ein Dataframe (d.h. eine Tabelle), indem wir Daten mit der `read_csv` Methode von pandas einlesen.

In [3]:
df = pd.read_csv('daten/periodic_table.csv')

Wir können uns die ersten paar Zeilen mit der Methode `head` anzeigen lassen:

In [4]:
# Zeige die ersten 10 Zeilen des Dataframes
df.head(n = 10)

,Name,Symbol,Atomic_Number,Atomic_Weight,Density,Melting_Point,Boiling_Point,Atomic_Radius,Covalent_Radius,Ionic_Radius,...,Specific_Heat,Heat_Fusion,Heat_Evaporation,Thermal_Conductivity,Pauling_Electronegativity,First_Ionisation_Energy,Oxidation_States,Electronic_Configuration,Lattice,Lattice_Constant
0,Hydrogen,H,1,1.00794,0.0708 (@ -253degC),14.01,20.28,79,32,NaN,...,14.267 (H-H),0.117 (H-H),0.904 (H-H),0.1815,2.2,1311.3,1 -1,1s¹,HEX,3.75
1,Helium,He,2,4.002602,0.147 (@ -270degC),0.95,4.216,0,-,NaN,...,5.188,-,0.08,0.152,-,2361.3,-,1s²,HEX,3.57
2,Lithium,Li,3,6.941,0.534,553.69,1118.15,155,163,NaN,...,3.489,2.89,148,84.8,0.98,519.9,1,[He]2s¹,BCC,3.49
3,Beryllium,Be,4,9.01218,1.848,1551,3243,112,90,NaN,...,1.824,12.21,309,201,1.57,898.8,2,[He]2s²,HEX,2.29
4,Boron,B,5,10.811,2.34,2573,3931,98,82,NaN,...,1.025,23.6,504.5,27.4,2.04,800.2,3,[He]2s²2p¹,TET,8.73
5,Carbon,C,6,12.011,2.25 (graphite),3820,5100,91,77,NaN,...,0.711,-,-,1.59,2.55,1085.7,4 2 -4,[He]2s²2p²,DIA,3.57
6,Nitrogen,N,7,14.00674,0.808 (@ -195.8degC),63.29,77.4,92,75,NaN,...,1.042 (N-N),-,-,0.026,3.04,1401.5,5 4 3 2 -3,[He]2s²2p³,HEX,4.039
7,Oxygen,O,8,15.9994,1.149 (@ -183degC),54.8,90.19,-,73,NaN,...,0.916 (O-O),-,-,0.027,3.44,1313.1,-2 -1,[He]2s²2p,CUB,6.83
8,Fluorine,F,9,18.998403,1.108 (@ -189degC),53.53,85.01,-,72,NaN,...,0.824 (F-F),0.51 (F-F),6.54 (F-F),0.028,3.98,1680,-1,[He]2s²2p,MCL,-
9,Neon,Ne,10,20.1797,1.204 (@ -246degC),48,27.1,-,71,NaN,...,1.029,-,1.74,<0.0493>,0,2079.4,-,[He]2s²2p,FCC,4.43

Um eine Spalte auszuwählen, nutzen wir den Namen der Spalte als "Index":

In [5]:
df['Atomic_Weight']

0       1.00794
1      4.002602
2         6.941
3       9.01218
4        10.811
         ...
113       [289]
114           -
115           -
116           -
117           -
Name: Atomic_Weight, Length: 118, dtype: object

Wir können auch mehrere Spaltennamen als Liste angeben. In diesem Fall ist das Resultat eine neue Tabelle, die nur aus den entsprechenden Spalten besteht:

In [6]:
df[['Symbol', 'Melting_Point', 'Boiling_Point']]

    Symbol Melting_Point Boiling_Point
0        H         14.01         20.28
1       He          0.95         4.216
2       Li        553.69       1118.15
3       Be          1551          3243
4        B          2573          3931
..     ...           ...           ...
113    Uuq             -             -
114    Uup             -             -
115    Uuh             -             -
116    Uus             -             -
117    Uuo             -             -

[118 rows x 3 columns]

Um einzelne Spalten zu entfernen, können Sie die Methode `drop` wie nachfolgend angegeben nutzen. 

*Beachten Sie, dass diese nicht das Dataframe `df` verändert, sondern ein neues Dataframe zurückgibt, aus welchem die entsprechenden Spalten entfernt sind.*

In [7]:
df_with_dropped_column = df.drop(columns = ["Symbol", "Melting_Point"])

Um einzelne Zeilen auszuwählen, nutzen wir die Methode `iloc`. Wir können einzelne Indizes, oder wie bei Numpy einen Bereich angeben.

In [8]:
df.iloc[5:10]

,Name,Symbol,Atomic_Number,Atomic_Weight,Density,Melting_Point,Boiling_Point,Atomic_Radius,Covalent_Radius,Ionic_Radius,...,Specific_Heat,Heat_Fusion,Heat_Evaporation,Thermal_Conductivity,Pauling_Electronegativity,First_Ionisation_Energy,Oxidation_States,Electronic_Configuration,Lattice,Lattice_Constant
5,Carbon,C,6,12.011,2.25 (graphite),3820,5100,91,77,NaN,...,0.711,-,-,1.59,2.55,1085.7,4 2 -4,[He]2s²2p²,DIA,3.57
6,Nitrogen,N,7,14.00674,0.808 (@ -195.8degC),63.29,77.4,92,75,NaN,...,1.042 (N-N),-,-,0.026,3.04,1401.5,5 4 3 2 -3,[He]2s²2p³,HEX,4.039
7,Oxygen,O,8,15.9994,1.149 (@ -183degC),54.8,90.19,-,73,NaN,...,0.916 (O-O),-,-,0.027,3.44,1313.1,-2 -1,[He]2s²2p,CUB,6.83
8,Fluorine,F,9,18.998403,1.108 (@ -189degC),53.53,85.01,-,72,NaN,...,0.824 (F-F),0.51 (F-F),6.54 (F-F),0.028,3.98,1680,-1,[He]2s²2p,MCL,-
9,Neon,Ne,10,20.1797,1.204 (@ -246degC),48,27.1,-,71,NaN,...,1.029,-,1.74,<0.0493>,0,2079.4,-,[He]2s²2p,FCC,4.43

Mit diesen Funktionen sollten Sie durch das Übungsblatt kommen. Pandas bietet aber viele weitere Funktionen. Wenn Sie mehr erfahren möchten, können wir das Buch [Python for Data Science, Kapitel 3](https://jakevdp.github.io/PythonDataScienceHandbook/03.00-introduction-to-pandas.html) empfehlen oder natürlich die offizielle [Pandas Dokumentation](https://pandas.pydata.org/docs/).

# Regression mit Scikit-Learn

In den nachfolgenden Aufgaben werden Sie ein Regressionsmodell trainieren um die effektivität von verschiedenen Werbemassnahmen zu prognostiezieren. Dabei werden Sie die Bibliothek [Scikit-Learn](https://scikit-learn.org/stable/) verwenden.

## Aufgabe 1: Laden und Vorbereiten der Daten


Verwenden Sie pandas, um den Datensatz `Advertising.csv` in ein DataFrame `df` zu laden. Wenn Sie `df.head()` ausführen, sollten Sie die folgenden Spalten sehen:

* TV: Werbung für das Produkt im Fernsehen (in Tausend Dollar).
* radio: Werbung für das Produkt im Radio (in Tausend Dollar).
* newspaper: Werbung für das Produkt in Zeitungen (in Tausend Dollar).
* sales: Verkaufszahlen des Produkts (in Tausend Einheiten).

In [9]:
df = pd.read_csv('daten/Advertising.csv')

Der Datensatz enthält unter anderem die Information, die wir Vorhersagen wollen (hier in der Spalte `sales`).  Wir spalten diese Information als Zielvariable `y` ab. Die restlichen Spalten sind die Merkmale, die wir verwenden wollen, um Vorhersagen zu machen. Diese speichern wir in der Variablen `X`.

In [11]:
# Aufteilen der Daten in Zielwert (y) und alle anderen Spalten (X)

y = df['sales']
X = df.drop(columns=['sales'])

Um die Performance eines Modells einschätzen zu können, teilen wir die Daten immer in ein Trainings- und ein Testsset auf. Das Trainingsset verwenden wir um das Modell zu trainieren, und das Testsset um die Vorhersage zu evaluieren. In scikit-learn können Sie dies mit der Funktion `train_test_split` machen. Verwenden Sie 30% der Daten für den Test.

Schauen Sie sich auch die [Dokumentation](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) der Funktion `train_test_split` an, um zu verstehen, was die Funktion genau macht und welche Parameter sie hat.

In [16]:
# split the data into train and test 

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7)

(140, 3) (60, 3)

Nun müssen wir die Daten noch standardisieren. Das bedeutet, dass wir von jedem Messwert den Durchschnittswert abziehen und durch die Standardabweichung teilen. Wir nutzen dazu den `StandardScaler` von scikit-learn (siehe [Dokumentation](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)). Wichtig hier ist, dass wir den `StandardScaler` nur auf den Trainingsdaten fitten, und dann die gleichen Transformationen auf die Testdaten anwenden. Das ist wichtig, damit wir keine Informationen aus dem Testset in das Training einfliessen lassen.

In [19]:
scaler = StandardScaler()
scaler.fit(X_train)  # fit scaler on training data

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

[[ 0.22820064  0.62641701  1.02127025]
 [ 0.65600359 -1.32452889 -0.47857996]
 [ 0.63021821 -1.26398229 -1.20248243]
 [ 0.60443282  1.70952836  1.02127025]
 [-0.4269825  -0.55760533 -0.965913  ]
 [ 1.78821633  0.9426048   3.29233681]
 [ 1.1260008   1.29242958 -0.60632746]
 [-1.48418322 -1.22361789  0.01348446]
 [-0.36251905 -0.32887374  0.34468167]
 [-1.54864667  0.9829692   0.65695332]
 [ 0.8165762   1.39334057  0.11757501]
 [ 0.87517935 -1.1361617  -0.18523387]
 [ 1.68507479  1.39334057  1.91550271]
 [ 1.16467888  1.79698455  0.61437082]
 [-1.59435713  1.11751719  0.91244831]
 [ 1.12834493 -1.0083411  -1.07000355]
 [ 0.48136622 -0.08668735 -0.44072886]
 [ 0.06997215 -1.41198508 -0.33190692]
 [ 0.96073994 -0.94779451  1.19160024]
 [-0.05426651 -0.53742313 -0.27039886]
 [-0.212495    0.9829692   2.26562547]
 [ 1.72140874 -1.22361789 -1.07946633]
 [-0.54301673 -0.9881589  -1.14097438]
 [-0.01090018  0.47168682 -0.88547939]
 [-0.27344227  0.41786762 -0.80977717]
 [ 1.55731994 -1.34471109 -0.36029525]
 [ 0.14967243 -1.32452889 -1.0889291 ]
 [-1.05872439 -1.36489328 -0.46911719]
 [-0.48206946  0.49186902 -1.08419772]
 [ 0.2422654  -0.09341475  0.76104387]
 [ 1.55966407  1.79025715  0.4960861 ]
 [-0.06950333  1.62207216  1.30988496]
 [ 1.39323114  0.43804982 -0.72934356]
 [ 0.57864744 -0.26159974  1.626888  ]
 [ 0.38877326  0.74751021  0.34941305]
 [ 0.73804799 -1.1496165  -0.56374496]
 [ 1.63819228  1.32606658  1.65054494]
 [-0.79149406  0.35059363 -0.72461218]
 [-0.3261851  -0.9814315  -0.38868358]
 [-0.58521099  1.42697757  0.90771692]
 [ 1.01113864  1.04351579  1.7924866 ]
 [ 0.32196567  1.17133639  0.30209917]
 [ 0.99004151 -0.36251074 -0.24201053]
 [-0.87705465 -0.87379311 -1.43905187]
 [ 0.30907298 -0.9747041   0.18381445]
 [ 0.51535605 -0.07995995 -1.03215244]
 [ 1.66632179 -0.56433273 -1.30657298]
 [ 0.87400728  0.36404843  1.04492719]
 [ 1.12482874 -1.22361789  0.26424806]
 [-0.66373921 -0.70560812 -0.2562047 ]
 [-1.67757359  1.16460899 -1.07000355]
 [-0.62623319 -1.47925908 -0.38395219]
 [ 0.38877326 -0.87379311 -1.17882549]
 [-0.398853    1.71625576  0.95029942]
 [ 1.42722096 -0.15396135 -1.4674402 ]
 [-0.90166797 -0.71233552  0.25951667]
 [-0.38830443  1.23188298  1.50860328]
 [ 0.81540414  0.15549904 -0.86182245]
 [ 0.51652811 -0.34232854 -0.63471579]
 [ 1.74719413  0.40441283  0.56232554]
 [ 0.93964281 -1.33798369 -0.74353773]
 [-0.87471052 -0.12032435 -0.61579024]
 [-0.74578361 -1.49944128 -1.04634661]
 [ 0.97714882 -0.43651213  0.87932859]
 [ 0.63021821  0.06804284 -0.80977717]
 [-1.0270787  -1.1159795  -0.07641193]
 [ 0.08989722  1.27897478  1.28622801]
 [-1.25328683  1.09733499  1.62215661]
 [-1.47597878  1.03006099 -0.45965441]
 [-0.56411386 -1.40525768 -1.1315116 ]
 [-1.31657823  0.15549904 -1.37754381]
 [-0.0894284  -0.20778054 -0.69622384]
 [-1.45839783 -0.42305733 -0.42653469]
 [-1.35056805 -1.39853028  0.0797239 ]
 [-0.398853   -0.53742313  0.01821585]
 [-0.91104447 -1.1092521  -0.3366383 ]
 [-0.50902691 -0.85361091 -1.31130437]
 [-0.98722856 -0.69215332  0.55759416]
 [-0.31212034 -0.51051353 -1.22613938]
 [-0.76922486  1.64898176  0.15069473]
 [ 1.12834493 -0.37596554 -0.39814636]
 [ 0.43331164 -0.77288211  1.28149662]
 [ 1.25492772  0.9560596   1.93915965]
 [-1.16186593  0.23622783 -0.5069683 ]
 [-1.2228132   1.26551998 -1.20721382]
 [ 1.06270941 -1.27070969  2.53058323]
 [-0.65084651  0.21604563  1.99120492]
 [-1.48769941  1.44043237  2.74822711]
 [-0.81024706  1.82389415  0.68061026]
 [ 1.28891754 -0.06650515 -0.06221776]
 [ 0.06880009  0.895513   -1.19775104]
 [-0.04137382 -1.37162068 -1.05580938]
 [-0.80555881  0.8551486   1.01180747]
 [-1.48418322  1.58843516  1.79721799]
 [-1.45605371 -0.14723395 -0.67729829]
 [ 0.71695086  1.53461597 -0.55428218]
 [-1.37166518  0.72060061 -0.56847635]
 [-1.11967166  1.66243656 -1.07946633]
 [ 1.42253271 -1.30434669  0.55286277]
 [ 0.78493051  1.83734895  0.30209917]
 [ 0.37353644 -0.46342173 -1.36808104]
 [ 1.2303144   0.32368403 -0.39814636]
 [ 0.33603043 -0.28178194 -0.02909804]
 [ 1.11896843 -0.45669433 -0.18996526]
 [-0.790322    0.29677443 -0.42653469]
 [-0.82548388 -0.35578334 -0.87128522]
 [-1.58732475  0.33041143 -1.3822752 ]
 [ 1.14709793  1.05697059 -0.38395219]
 [-0.05075032 -1.35816589 -0.22308498]
 [ 1.09669923 -1.1563439  -0.36975803]
 [ 0.83064096  0.11513464 -1.29237882]
 [-0.05309445 -0.52396833 -0.99903272]
 [ 0.9208898  -1.21016309  0.8745972 ]
 [-0.55825355 -0.50378613  0.35887583]
 [-1.39276231 -0.75942732 -0.07641193]
 [-0.26758195 -0.93433971  0.82255192]
 [-1.53223779 -1.47253168 -0.27039886]
 [ 1.6124069   1.16460899  1.15848052]
 [ 0.65600359 -1.29089189  0.15542612]
 [ 0.25515809 -0.82670131 -0.64890996]
 [-0.63443763 -0.83342871  0.20747139]
 [ 1.30767055  0.31022923 -1.22140799]
 [-1.62248664  0.51205122 -1.03688383]
 [ 0.36650406  0.01422364  0.00875307]
 [-0.14217123 -0.26159974  0.15542612]
 [-1.181791    0.24295523 -0.51169969]
 [-1.53106573 -0.42978473  0.86513442]
 [-1.23805001 -1.25052749 -0.82870273]
 [-0.1492036   1.37988578 -0.11426304]
 [ 0.64779915  0.55914302  0.34941305]
 [-1.01184188  0.70714581 -0.36975803]
 [-0.95558286 -0.65178892 -0.61579024]
 [-1.46660227 -0.68542592 -0.37448941]
 [ 1.39557526 -1.26398229 -0.55901357]
 [-1.16421005  1.14442679  0.65222193]
 [ 1.00410626  0.67350881  2.02905603]
 [-0.80321469 -0.13377915  0.05606696]
 [ 0.45440878  1.60861736  1.29569079]
 [-1.18061893  0.29677443  0.17908306]
 [ 1.70968811  1.34624878  0.94083664]]
[[-1.39159025e+00  2.29500434e-01  5.67056933e-01]
 [ 1.52215805e+00  4.44777223e-01  1.34300468e+00]
 [-1.11697592e-01 -1.16979869e+00 -1.04161522e+00]
 [-7.90321996e-01 -1.44562208e+00 -7.81388840e-01]
 [ 6.87649288e-01  7.68845675e-04  1.34844577e-02]
 [-8.91119403e-01  9.62786997e-01  3.91214873e+00]
 [ 1.60420245e+00 -5.64332726e-01  2.68979446e-01]
 [-8.58301642e-01 -4.23057333e-01  4.48772216e-01]
 [ 7.83758444e-01  4.85141621e-01 -1.04161522e+00]
 [-8.00870561e-01 -7.72882115e-01 -1.19775104e+00]
 [ 2.87975848e-01 -1.02179590e+00 -8.76016614e-01]
 [ 7.70865752e-01 -1.13596948e-01 -9.75375776e-01]
 [ 8.65802845e-01  7.54237607e-01  1.30988496e+00]
 [-8.84087025e-01  1.49425157e+00  2.02740005e-01]
 [ 1.37682226e+00  1.37315838e+00  1.10643524e+00]
 [-2.76958457e-01 -1.80870945e-01 -9.32793278e-01]
 [ 5.22388423e-01 -2.81781940e-01 -2.70398863e-01]
 [ 2.69222842e-01  1.32606658e+00 -1.31130437e+00]
 [-1.46543021e+00 -3.95955523e-02  9.02985529e-01]
 [-1.38572994e+00  1.12424459e+00 -1.04161522e+00]
 [-1.69128673e-01 -1.11597950e+00 -7.09708302e-04]
 [ 1.22562615e+00  5.32233419e-01 -5.21162463e-01]
 [-1.58498062e+00 -1.35816589e+00 -1.43432048e+00]
 [-5.81694804e-01 -1.16979869e+00 -1.09839188e+00]
 [-6.81320148e-01  9.08967799e-01  8.50940254e-01]
 [-1.63772345e+00 -7.19062918e-01 -1.21194521e+00]
 [ 5.84507755e-01  8.82058201e-01  2.09529548e+00]
 [ 1.44245778e+00  1.44715977e+00 -1.24506493e+00]
 [ 8.50566027e-01  1.30588438e+00  3.91995552e-01]
 [-1.40682707e+00  8.61876002e-01  1.63635077e+00]
 [-5.46532918e-01 -1.39853028e+00 -6.22177611e-02]
 [ 1.75539857e+00  3.64048427e-01 -1.39646937e+00]
 [ 2.30544767e-01  9.76241796e-01 -1.13151160e+00]
 [ 9.86525321e-01  1.03678839e+00  3.24100124e-02]
 [ 1.09669923e+00  3.50593628e-01 -9.61181610e-01]
 [ 1.59834214e+00 -8.19973913e-01 -4.69117187e-01]
 [ 4.81366222e-01  1.45388717e+00 -1.40120076e+00]
 [-2.42968634e-01  8.28239004e-01 -8.94942168e-01]
 [ 7.39220054e-01 -9.34339707e-01 -2.32547753e-01]
 [ 1.10607573e+00  8.08056805e-01 -1.23087076e+00]
 [ 8.98620605e-01  7.34055408e-01  3.11561944e-01]
 [ 8.90416165e-01  7.54237607e-01  6.52221929e-01]
 [ 7.06402294e-01  7.13873209e-01  6.94804427e-01]
 [-1.01149026e-01  1.30588438e+00  6.90073039e-01]
 [-1.36346074e+00 -1.39180288e+00 -5.02236908e-01]
 [ 8.55254279e-01  1.45388717e+00 -1.94696644e-01]
 [ 9.20889800e-01 -1.27070969e+00 -8.61822448e-01]
 [ 6.45455024e-01  1.82389415e+00  1.35719884e+00]
 [-4.59800265e-01 -1.11597950e+00  1.45963341e-01]
 [ 8.96276479e-01  1.79698455e+00 -1.33022993e+00]
 [ 8.38845399e-01  8.82250412e-02  1.24364551e+00]
 [-1.09974659e+00 -7.19062918e-01 -6.11058848e-01]
 [ 1.03457990e+00 -9.20884907e-01 -1.07000355e+00]
 [-1.24039414e+00  1.21170078e+00 -9.18599112e-01]
 [ 1.64639672e+00 -7.86336914e-01 -1.17882549e+00]
 [-1.58380856e+00  1.79025715e+00  2.06690714e+00]
 [ 5.54034120e-01  4.31322424e-01 -6.20521625e-01]
 [-1.60021744e+00  3.90958026e-01  4.77160548e-01]
 [-2.96531907e-02  3.03501830e-01  7.04267205e-01]
 [ 4.06705817e-02  1.08407240e-01 -5.77939127e-01]]

## Aufgabe 2: Lineare Regression

Nun können wir ein  lineares Regressionsmodell erstellen und diees auf den Datensatz anpassen. 
Details, wie dies in scikit-learn gemacht wird, finden Sie in der [Dokumentation](tps://scikit-learn.org/stable/index.html) oder in den Vorlesungsnotebooks.

In [20]:
model = LinearRegression()
model.fit(X_train_scaled, y_train)

LinearRegression()

Nun können wir das Modell nutzen um Vorhersagen zu treffen und die Vorhersagen mit den tatsächlichen Werten zu vergleichen. 

Wir machen dies sowohl mit den Trainingsdaten, als auch mit den Testdaten. 

Um die Qualität der Vorhersage zu beurteilen, verwenden wir den `r2_score` (siehe [Dokumentation von scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html#sklearn.metrics.r2_score). 

Der `r2_score` (auch Coefficient of determination oder Bestimmtheitsmass genannt) ist eine dimensionslose Grösse, die typischwerweise zwischen 0 und 1 liegt. Ein Wert von 1 bedeutet, dass die Daten perfekt erklärt wurden. Bei einem Wert von 0 ist die Vorhersage nicht besser, als wenn man einfach den Durchschnitt der Zielwerte für die Vorhersage verwendet hätte. Negative Werte bedeuten, dass die Vorhersage sogar schlechter ist, als wenn man die Messwerte gar nicht verwendet hätte und immer nur den Mittelwert schätzen würde. Welchen Wert erreichen Sie?

In [21]:
# Vorhersagen und berechnen des r2 Werts auf Trainingsdaten und Testdatan
y_pred_train = model.predict(X_train_scaled)
r2_train = r2_score(y_train, y_pred_train)
y_pred_test = model.predict(X_test_scaled)
r2_test = r2_score(y_test, y_pred_test)

print("R2 train: ", r2_train)
print("R2 test: ", r2_test)

R2 train:  0.885924431799408
R2 test:  0.9132804488047827

### Aufgabe 3: Polynomiale Regression

In dieser Aufgabe transformieren wir die Daten, indem wir auf den Merkmalen mittels Polynomen transformieren. Scikit-learn stellt dafür die Klasse [PolynomialFeatures](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html) zur Verfügung. Damit lassen sich die Daten so transformieren, dass sie alle möglichen Kombinationen der Merkmale bis zu einem bestimmten Grad enthält. 

Machen Sie dies sowohl für die Trainings- als auch für die Testdaten. Nutzen Sie dazu die standardisierten Daten, die Sie in Aufgabe 1 erstellt haben. Verwenden Sie ein Polynom von Grad 2.

In [40]:
# Transformieren der Daten mithilfe von PolynomialFeatures

poly = PolynomialFeatures(degree=1, include_bias=False)
X_poly_train = poly.fit_transform(X_train_scaled)
X_poly_test = poly.transform(X_test_scaled)

print(X_poly_test.shape)

(60, 3)


Nun können sie das Lineare Regressionsmodell wieder verwenden, um aus den Daten zu lernen. Wird die Vorhersage besser? Was beobachten Sie, wenn Sie den Grad der PolynomialFeatures erhöhen (z.B. auf Grad 5 oder noch höher)? Weshalb ist das problematisch?

In [42]:

regr_poly = linear_model.LinearRegression()

regr_poly.fit(X_train_scaled, y_train)

y_pred_train = regr_poly.predict(X_train_scaled)
r2_train = r2_score(y_train, y_pred_train)
y_pred_test = regr_poly.predict(X_test_scaled)
r2_test = r2_score(y_test, y_pred_test)

print(r2_train, r2_test)

0.885924431799408 0.9132804488047827

*Ihre Antwort*:

Versuchen Sie nun auf den Polynomialen Features eine ridge Regression zu machen. Haben Sie hier auch das Problem von Overfitting? Ist das Modell besser, als wenn Sie nur die lineare Regression verwenden? Welcher Einfluss hat der Regularisierungsparameter `alpha` auf das Modell?

In [ ]:
ridge_regr = Ridge(alpha=1.0)

# Anpassen des Modells auf den Trainingsdaten
...

# Vorheragen berechnen
y_pred_train_ridge = ...
y_pred_test_ridge = ...

# Metriken berechnen
r2_train_ridge = ...
r2_test_ridge = ...

print("R2 train (Ridge):", r2_train_ridge)
print("R2 test (Ridge):", r2_test_ridge)

### Aufgabe 3: Kreuzvalidierung und finden der besten Hyperparameter

In dieser Aufgabe sollen Sie Kreuzvalidierung verwenden, um die besten Hyperparameter für den Parameter `alpha` der Ridge Regression zu finden. Nutzen Sie dafür die Klasse `GridSearchCV` und wählen Sie 4-fache Kreuzvalidierung. Probieren Sie Werte von alpha zwischen 0.01 und 1000 (z.B. 0.01, 0.1, 1, 10, 100, 1000).

Geben Sie die besten Hyperparameter aus. 

Auch hier finden Sie wieder Beispiele in der [Dokumentation von scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV) oder in den Vorlesungsnotizen.

*Hinweis:* Eventuell werden Sie bemerken, dass das beste Modell einen schlechteren R2-Score auf dem Testset hat, als das Modell mit den Standardparametern. Das ist nicht ungewöhnlich, da die Kreuzvalidierung nur auf dem Trainingsset durchgeführt wird und wir nur 200 Datenpunkte haben. Es könnte also sein, dass das beste Modell für das Trainingsset nicht unbedingt das beste Modell für das Testset ist.

In [ ]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = ... 

# Initialize the GridSearchCV
grid_search = ...

# Fit the GridSearchCV on the training data
grid_search.fit(..., ...)

# Print the best parameters and the best score
print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy:", grid_search.best_score_)